/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as ApiPublicSyncFuenteRouteImport } from './routes/api/public/sync/$fuente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncFuenteRoute = ApiPublicSyncFuenteRouteImport.update({
  id: '/api/public/sync/$fuente',
  path: '/api/public/sync/$fuente',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/api/public/sync/$fuente': typeof ApiPublicSyncFuenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/api/public/sync/$fuente': typeof ApiPublicSyncFuenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/api/public/sync/$fuente': typeof ApiPublicSyncFuenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/api/public/sync/$fuente'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/api/public/sync/$fuente'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/api/public/sync/$fuente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  ApiPublicSyncFuenteRoute: typeof ApiPublicSyncFuenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/$fuente': {
      id: '/api/public/sync/$fuente'
      path: '/api/public/sync/$fuente'
      fullPath: '/api/public/sync/$fuente'
      preLoaderRoute: typeof ApiPublicSyncFuenteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  ApiPublicSyncFuenteRoute: ApiPublicSyncFuenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
